### ISSUE TITLE
v0.4.4 - 193534

### ISSUE THREAD

**Issue by slarosa89** [CYCNO/DirectDownload#1]
Hello,

When trying to get a direct download link for any mediafire URL (including the one in the example on your website) I get an error of "193534"

`>>> from Direct_Download import Direct
>>> url = Direct()
>>> 
>>> url.mediafire('https://www.mediafire.com/file_premium/6mz208axw5ie6xg/Phish_-_02_26_2023_Moon_Palace_Resort%252C_Riviera_Maya%252C_MX_1080p.mkv/file')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/Direct_Download.py", line 11, in mediafire
    down_link = down['data']['file']['url']['directDownload']
TypeError: string indices must be integers
>>> url.mediafire('https://www.mediafire.com/view/n2kcs3n9nd88vnr/picture.jpeg/file')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/dist-packages/Direct_Download.py", line 11, in mediafire
    down_link = down['data']['file']['url']['directDownload']
TypeError: string indices must be integers`

**Comment by slarosa89** [comment]
It actually looks like the problem is that your API behind the scenes is returning JSON that does not match what your python is handling:


https://ddl-api.cycno.repl.co/mediafire?link=https://www.mediafire.com/file_premium/6mz208axw5ie6xg/Phish_-_02_26_2023_Moon_Palace_Resort%252C_Riviera_Maya%252C_MX_1080p.mkv/file

"{'status': 'false', 'message': 'Invalid Link'}"

**Comment by PandoricGalaxy** [comment]
yup same problem

**Comment by CYCNO** [comment]
hi @slarosa89 first of all sorry for late reply 

I will suggest you to use [api ](https://github.com/CYCNO/Direct-Download-API)rather than this module for now because I am not managing this module right now (maybe i will do it in future) 

if you think that [api ](https://github.com/CYCNO/Direct-Download-API)is not working than you can simply host it on your local pc for better result btw the [api ](https://github.com/CYCNO/Direct-Download-API)is working right now for me 

`https://ddl-api.cycno.repl.co/mediafire?link=https://www.mediafire.com/file_premium/6mz208axw5ie6xg/Phish_-_02_26_2023_Moon_Palace_Resort%252C_Riviera_Maya%252C_MX_1080p.mkv/file`

```json
{
  "status": "true",
  "data": {
    "file": {
      "url": {
        "directDownload": "https://download848.mediafire.com/1otgysodlcegZ3uDSyQC4TRIV9x_2R1rqggFbWYCtOiqPz5nEIjcjJcUemPsp07tk76oaQaG1kh0oGjzFZQtu6oblPowtrLfyJJQEaWm2ygQ3Nur85Kb2h2HZWAiQ9jJekdNqhWDx8Lj34F1gaVdRKJipo0A8-8RcglTFGx1Mwtk/6mz208axw5ie6xg/Phish+-+02_26_2023+Moon+Palace+Resort%2C+Riviera+Maya%2C+MX+1080p.mkv",
        "original": "https://www.mediafire.com/file_premium/6mz208axw5ie6xg/Phish_-_02_26_2023_Moon_Palace_Resort%2C_Riviera_Maya%2C_MX_1080p.mkv/file"
      },
      "metadata": {
        "id": "6mz208axw5ie6xg",
        "name": "Phish-02_26_2023MoonPalaceResort,RivieraMaya,MX1080p",
        "size": {
          "readable": "6GB"
        },
        "DateAndTime": {
          "time": "00:31:41",
          "date": "2023-02-28"
        }
      }
    }
  }
}
```

thanks
